apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8up
  namespace: flux
spec:
  interval: 10m0s
  path: "./flux/k8up/yaml"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
  postBuild:
    substituteFrom:
    - kind: Secret
      name: route53-credentials-secret
