apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matchering
  namespace: matchering
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchering
  namespace: matchering
spec:
  selector:
    matchLabels:
      app: matchering
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
        mariadb-client: "true"
        memcached-client: "true"
    spec:
      containers:
      - name: matchering
        image: bitnami/wordpress:6.8.1
        ports:
        - containerPort: 8360
        volumeMounts:
        - mountPath: /bitnami/wordpress
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: matchering
---
apiVersion: v1
kind: Service
metadata:
  name: matchering
  namespace: matchering
spec:
  ports:
  - port: 80
    targetPort: 8360
    protocol: TCP
  selector:
    app: matchering