apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cpu-requests-remover-webhook
  namespace: flux
spec:
  interval: 10m0s
  path: "./config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: cpu-requests-remover-webhook
  dependsOn:
  - name: cert-manager-manifests
