apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cpu-requests-remover-webhook
  namespace: flux
spec:
  interval: 10m0s
  ref:
    branch: main
  timeout: 60s
  url: ssh://git@github.com/bentastic27/cpu-requests-remover-webhook
