apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-operator
  namespace: flux
spec:
  interval: 10m0s
  path: "./flux/keycloak/manifests/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
  dependsOn:
  - name: istio
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux
spec:
  interval: 10m0s
  path: "./flux/keycloak/manifests"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
  dependsOn:
  - name: istio
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: common-configs
    - kind: Secret
      name: route53-credentials-secret
    - kind: Secret
      name: restic-password
