apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: istio-system
spec:
  secretName: argocd-cert
  commonName: argocd.beansnet.net
  dnsNames:
  - argocd.beansnet.net
  issuerRef:
    name: letsencrypt-dns-cluster-issuer
    kind: ClusterIssuer
