apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: istio-base
  targetNamespace: istio-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: base
      version: '1.24.2'
      sourceRef:
        kind: HelmRepository
        name: istio
