apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: beansnet
  namespace: istio-system
spec:
  secretName: beansnet-cert
  commonName: beansnet.net
  dnsNames:
  - beansnet.net
  - "*.beansnet.net"
  issuerRef:
    name: letsencrypt-dns-cluster-issuer
    kind: ClusterIssuer
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  addresses:
  - value: ingressgateway.istio-system.svc.cluster.local
    type: Hostname
  listeners:
  - name: base-http
    hostname: "beansnet.net"
    port: 8080
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: wildcard-http
    hostname: "*.beansnet.net"
    port: 8080
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: base-https
    protocol: HTTPS
    port: 8443
    hostname: "beansnet.net"
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: beansnet-cert
  - name: wildcard-https
    protocol: HTTPS
    port: 8443
    hostname: "*.beansnet.net"
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: beansnet-cert
