apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-gateway
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: ingress-gateway
  targetNamespace: istio-system
  chart:
    spec:
      chart: gateway
      version: '1.25.0'
      sourceRef:
        kind: HelmRepository
        name: istio
  values:
    profile: ambient
    kind: Deployment
    service:
      type: NodePort
      externalTrafficPolicy: Local
      ports:
      - name: status-port
        port: 15021
        protocol: TCP
        targetPort: 15021
      - name: http2
        port: 80
        protocol: TCP
        targetPort: 80
        nodePort: 30080
      - name: https
        port: 443
        protocol: TCP
        targetPort: 443
        nodePort: 30443
    resources:
      requests:
        cpu: "0"
    autoscaling:
      enabled: false
  dependsOn:
  - name: istio-base
  - name: istiod
