apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: ambient
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    defaultConfig:
      interceptionMode: TPROXY
      gatewayTopology:
        numTrustedProxies: 0
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        PILOT_ENABLE_IP_AUTOALLOCATE: "true"
    extensionProviders:
    - name: "oauth2-proxy"
      envoyExtAuthzHttp:
        service: "oauth2-proxy.oauth2-proxy.svc.cluster.local"
        port: "80"
        includeRequestHeadersInCheck: ["authorization", "cookie"]
        headersToUpstreamOnAllow: ["authorization", "path", "x-auth-request-user", "x-auth-request-email", "x-auth-request-access-token"]
        headersToDownstreamOnAllow: ["set-cookie"]
        headersToDownstreamOnDeny: ["content-type", "set-cookie"]
  components:
    cni:
      namespace: istio-system
      enabled: true
  values:
    pilot:
      env:
        ENABLE_NATIVE_SIDECARS: "true"
        PILOT_ENABLE_ALPHA_GATEWAY_API: "true"
    global:
      proxy:
        resources:
          requests:
            cpu: "0"
            memory: "0"
          limits:
            cpu: 2000m
            memory: 1024Mi
