apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    defaultConfig:
      interceptionMode: TPROXY
      gatewayTopology:
        numTrustedProxies: 0
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        PILOT_ENABLE_IP_AUTOALLOCATE: "true"
  components:
    ingressGateways:
      - name: ingressgateway
        enabled: true
        k8s:
          service:
            externalTrafficPolicy: Local
            type: NodePort
            ports:
            - name: status-port
              port: 15021
              protocol: TCP
              targetPort: 15021
            - name: http2
              nodePort: 30080
              port: 8080
              protocol: TCP
              targetPort: 8080
            - name: https
              nodePort: 30443
              port: 8443
              protocol: TCP
              targetPort: 8443
          overlays:
          - kind: Deployment
            name: ingressgateway
            patches:
            - path: kind
              value: DaemonSet
            - path: spec.strategy
              value: null
  values:
    pilot:
      env:
        ENABLE_NATIVE_SIDECARS: "true"
    global:
      proxy:
        resources:
          requests:
            cpu: "0"
            memory: "0"
          limits:
            cpu: 2000m
            memory: 1024Mi
