apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    defaultConfig:
      interceptionMode: TPROXY
      gatewayTopology:
        numTrustedProxies: 2
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        PILOT_ENABLE_IP_AUTOALLOCATE: "true"
  components:
    ingressGateways:
      - name: ingressgateway
        enabled: false
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: "0"
            memory: "0"
          limits:
            cpu: 2000m
            memory: 1024Mi
