apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: istio-cni
  targetNamespace: istio-system
  chart:
    spec:
      chart: cni
      version: '1.24.2'
      sourceRef:
        kind: HelmRepository
        name: istio
  values:
    profile: ambient
  dependsOn:
  - name: istio-base
