apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    defaultConfig:
      interceptionMode: TPROXY
      gatewayTopology:
        numTrustedProxies: 2
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        PILOT_ENABLE_IP_AUTOALLOCATE: "true"
  components:
    ingressGateways:
      - name: ingressgateway
        enabled: enabled
        k8s:
          service:
            externalTrafficPolicy: Local
            annotations:
              metallb.universe.tf/address-pool: host-ip
            ports:
            - name: status-port
              port: 15021
              protocol: TCP
              targetPort: 15021
            - name: http2
              nodePort: 30080
              port: 80
              protocol: TCP
              targetPort: 80
            - name: https
              nodePort: 30443
              port: 443
              protocol: TCP
              targetPort: 443
  values:
    pilot:
      env:
        ENABLE_NATIVE_SIDECARS: "true"
    global:
      proxy:
        resources:
          requests:
            cpu: "0"
            memory: "0"
          limits:
            cpu: 2000m
            memory: 1024Mi
