apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: istiod
  targetNamespace: istio-system
  chart:
    spec:
      chart: istiod
      version: '1.24.2'
      sourceRef:
        kind: HelmRepository
        name: istio
  values:
    profile: ambient
    global:
      proxy:
        resources:
          requests:
            cpu: "0"
            memory: 128Mi
          limits:
            cpu: 2000m
            memory: 1024Mi
    meshConfig:
      accessLogFile: /dev/stdout
      defaultConfig:
        interceptionMode: TPROXY
        gatewayTopology:
          proxyProtocol: {}
  dependsOn:
  - name: istio-base