apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kiali
  namespace: flux
spec:
  interval: 30m0s
  url: https://kiali.org/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: kiali-server
  targetNamespace: istio-system
  install:
    createNamespace: false
  chart:
    spec:
      chart: kiali-server
      version: '2.16.0'
      sourceRef:
        kind: HelmRepository
        name: kiali
  values:
    auth:
      strategy: anonymous
    deployment:
      view_only_mode: true
    external_services:
      prometheus:
        url: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090/
      grafana:
        enabled: true
        internal_url: http://prometheus-grafana.prometheus.svc.cluster.local:80/
        auth:
          username: "admin"
          password: "prom-operator"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kiali
  namespace: istio-system
spec:
  hostnames:
  - kiali.int.beansnet.net
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: internal-gateway
    namespace: istio-system
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: kiali
      port: 20001
      filters:
      - type: ExternalAuth
        externalAuth:
          protocol: HTTP
          http:
            path: /oauth2/auth
          backendRef:
            group: ""
            kind: Service
            name: oauth2-proxy
            namespace: oauth2-proxy
    matches:
    - path:
        type: PathPrefix
        value: /