apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kiali
  namespace: flux
spec:
  interval: 30m0s
  url: https://kiali.org/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: kiali-server
  targetNamespace: istio-system
  install:
    createNamespace: false
  chart:
    spec:
      chart: kiali-server
      version: '2.16.0'
      sourceRef:
        kind: HelmRepository
        name: kiali
  values:
    auth:
      strategy: anonymous
    deployment:
      view_only_mode: true
    external_services:
      prometheus:
        url: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090/
      grafana:
        enabled: true
        internal_url: http://prometheus-grafana.prometheus.svc.cluster.local:80/
        auth:
          username: "admin"
          password: "prom-operator"
  postRenderers:
  - kustomize:
      patches:
      - target:
          version: v1
          kind: Service
          name: kiali
        patch: |
          - op: add
            path: /metadata/labels/istio.io~1ingress-use-waypoint
            value: "true"
          - op: add
            path: /metadata/labels/istio.io~1dataplane-mode
            value: "ambient"
          - op: add
            path: /metadata/labels/istio.io~1use-waypoint
            value: "shared-waypoint"
          - op: add
            path: /metadata/labels/istio.io~1use-waypoint-namespace
            value: "istio-system"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kiali
  namespace: istio-system
spec:
  hostnames:
  - kiali.int.beansnet.net
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: internal-gateway
    namespace: istio-system
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: kiali
      port: 20001
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kiali-public
  namespace: istio-system
spec:
  hostnames:
  - beansnet.net
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: public-gateway
    namespace: istio-system
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: kiali
      port: 20001
    matches:
    - path:
        type: PathPrefix
        value: /kiali
    filters:
    - type: URLRewrite
      urlRewrite:
        path: /
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: ext-authz
  namespace: istio-system
spec:
  targetRefs:
  - kind: Service
    group: ""
    name: kiali
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
  - to:
    - operation:
        notPrinciples:
        - cluster.local/ns/istio-system/sa/internal-gateway-istio
