apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: ztunnel
  targetNamespace: istio-system
  chart:
    spec:
      chart: ztunnel
      version: '1.25.0'
      sourceRef:
        kind: HelmRepository
        name: istio
  values:
    profile: ambient
    meshConfig:
      accessLogFile: /dev/stdout
      defaultConfig:
        interceptionMode: TPROXY
        gatewayTopology:
          numTrustedProxies: 1
          proxyProtocol: {}
        proxyMetadata:
          ISTIO_META_DNS_CAPTURE: "true"
          PILOT_ENABLE_IP_AUTOALLOCATE: "true"
  dependsOn:
  - name: istio-base
  - name: istiod
