apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  namespace: istio-system
spec:
  secretName: {{ .Release.Name }}-cert
  commonName: {{ .Values.hostname }}
  dnsNames:
  - {{ .Values.hostname }}
  issuerRef:
    name: {{ .Values.clusterIssuer }}
    kind: ClusterIssuer
