apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingress-gateway
  servers:
  - name: http
    hostname: {{ .Values.hostname }}
    port: 80
    protocol: HTTP
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - {{ .Values.hostname }}
    tls:
      credentialName: {{ .Release.Name }}-cert
      maxProtocolVersion: TLSV1_3
      minProtocolVersion: TLSV1_2
