apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.hostname }}
    tls:
     httpsRedirect: true
  - port:
      number: 8443
      name: https
      protocol: HTTPS
    hosts:
    - {{ .Values.hostname }}
    tls:
      credentialName: {{ .Release.Name }}-cert
      maxProtocolVersion: TLSV1_3
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
