apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: prometheus
  targetNamespace: prometheus
  install:
    createNamespace: true
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '68.3.2'
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 5m
  values:
    alertmanager:
      enabled: false
