apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: public-ip-configmapper
  namespace: flux
spec:
  interval: 10m0s
  path: "./flux/public-ip-configmapper"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
