apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft-manifests
  namespace: flux
spec:
  interval: 10m0s
  path: "./flux/minecraft/manifests"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
  postBuild:
    substituteFrom:
    - kind: Secret
      name: route53-credentials-secret
    - kind: Secret
      name: restic-password
