apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-bedrock
  namespace: minecraft
  labels:
    app: minecraft
data:
  EULA: "TRUE" # Must accept EULA to use this minecraft server
  TYPE: PAPER
  PLUGINS: |
    https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
    https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
    https://github.com/ViaVersion/ViaVersion/releases/download/5.3.2/ViaVersion-5.3.2.jar
  MEMORY: 4G
  DIFFICULTY: peaceful
  VIEW_DISTANCE: "20"

  #GAMEMODE: "survival" # Options: survival, creative, adventure
  #DIFFICULTY: "easy" # Options: peaceful, easy, normal, hard
  #DEFAULT_PLAYER_PERMISSION_LEVEL: "member" # Options: visitor, member, operator
  #LEVEL_NAME: "my_minecraft_world"
  #LEVEL_SEED: "33480944"
  #SERVER_NAME: "my_minecraft_server"
  #SERVER_PORT: "19132"
  #LEVEL_TYPE: "DEFAULT" # Options: FLAT, LEGACY, DEFAULT
  #ALLOW_CHEATS: "false" # Options: true, false
  #MAX_PLAYERS: "10"
  #PLAYER_IDLE_TIMEOUT: "30"
  #TEXTUREPACK_REQUIRED: "false" # Options: true, false
  #
  ## Changing these will have a security impact
  #ONLINE_MODE: "true" # Options: true, false (removes Xbox Live account requirements)
  #WHITE_LIST: "false" # If enabled, need to provide a whitelist.json by your own means. 
  #
  ## Changing these will have a performance impact
  #VIEW_DISTANCE: "10"
  #TICK_DISTANCE: "4"
  #MAX_THREADS: "8"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft
  namespace: minecraft
spec:
  storageClassName: openebs-hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: minecraft
  name: minecraft
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: main
          image: itzg/minecraft-server
          imagePullPolicy: Always
          resources:
            limits:
              memory: 6Gi
              cpu: 2
          envFrom:
          - configMapRef:
              name: minecraft-bedrock
          volumeMounts:
          - mountPath: /data
            name: data
          ports:
          - containerPort: 19132
            protocol: UDP
            name: bedrock
          - containerPort: 25565
            protocol: TCP
            name: java
          # readinessProbe: &probe
          #   exec:
          #     command:
          #     - mc-monitor
          #     - status-bedrock
          #     - --host
          #     # force health check against IPv4 port
          #     - 127.0.0.1
          #   initialDelaySeconds: 30
          # livenessProbe: *probe
          tty: true
          stdin: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
spec:
  selector:
    app: minecraft
  ports:
  - port: 19132
    protocol: UDP
    name: bedrock
    nodePort: 39132
  - port: 25565
    protocol: TCP
    name: java
    nodePort: 35565
  type: NodePort