apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-ip-configmapper
  namespace: flux
  labels:
    app: public-ip-configmapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-ip-configmapper
  template:
    metadata:
      labels:
        app: public-ip-configmapper
    spec:
      serviceAccountName: public-ip-configmapper
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: public-ip-configmapper
        image: bentastic27/public-ip-configmapper:latest
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIGMAP_NAME
          value: "common-configs"
        - name: CONFIGMAP_KEY
          value: "publicIp"
        - name: IP_URL
          value: "https://api.ipify.org"
        - name: INTERVAL
          value: "300"
