apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: openebs
  targetNamespace: openebs
  install:
    createNamespace: true
  chart:
    spec:
      chart: openebs
      version: '4.4.0'
      sourceRef:
        kind: HelmRepository
        name: openebs
  values:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
    loki:
      enabled: false
      minio:
        enabled: false
