apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak-postgresql
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: postgresql
  targetNamespace: keycloak
  chart:
    spec:
      chart: postgresql
      version: '18.1.8'
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 5m
  values:
    auth:
      user: keycloak
      database: keycloak
    global:
      defaultStorageClass: openebs-hostpath
    primary:
      resources:
        limits:
          memory: 512Mi
    networkPolicy:
      enabled: false
  # postRenderers:
  # - kustomize:
  #     patches:
  #     - target:
  #         version: v1
  #         kind: Service
  #         name: mariadb
  #       patch: |
  #         - op: add
  #           path: /metadata/labels/istio.io~1ingress-use-waypoint
  #           value: "true"
  #     - target:
  #         version: v1
  #         kind: Service
  #         name: mariadb-headless
  #       patch: |
  #         - op: add
  #           path: /metadata/labels/istio.io~1ingress-use-waypoint
  #           value: "true"