apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8up
  namespace: flux
spec:
  interval: 10m0s
  url: https://k8up-io.github.io/k8up
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8up
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: k8up
  targetNamespace: k8up
  chart:
    spec:
      chart: k8up
      version: '4.8.6'
      sourceRef:
        kind: HelmRepository
        name: k8up
  values:
    k8up:
      timezone: America/Detroit
    metrics:
      serviceMonitor:
        enabled: true
        namespace: prometheus
      prometheusRule:
        enabled: true
        namespace: prometheus
      grafanaDashboard:
        enabled: false
        namespace: prometheus