apiVersion: v1
kind: Secret
metadata:
  name: ollama-api-key
  namespace: flux
  annotations:
    secret-generator.v1.mittwald.de/type: string
    secret-generator.v1.mittwald.de/secure: "yes"
    secret-generator.v1.mittwald.de/length: "48"
    secret-generator.v1.mittwald.de/autogenerate: OLLAMA_API_KEY
