apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: coredns
  namespace: flux
spec:
  interval: 10m0s
  url: https://coredns.github.io/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: coredns
  targetNamespace: coredns
  chart:
    spec:
      chart: coredns
      version: '1.45.0'
      sourceRef:
        kind: HelmRepository
        name: coredns
  values:
    isClusterService: false
    serviceType: LoadBalancer
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.1.11
    servers:
    - zones:
      - zone: .
        use_tcp: true
      port: 53
      plugins:
      - name: errors
      - name: health
        configBlock: |-
          lameduck 10s
      - name: ready
      - name: hosts
        configBlock: |-
          192.168.1.12 geo.hivebedrock.network
          192.168.1.12 hivebedrock.network
          192.168.1.12 play.inpvp.net
          192.168.1.12 mco.lbsg.net
          192.168.1.12 play.galaxite.net
          192.168.1.12 play.enchanted.gg
          192.168.1.12 mco.cubecraft.net
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . /etc/resolv.conf
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
    