apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: coredns
  namespace: flux
spec:
  interval: 10m0s
  url: https://coredns.github.io/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: coredns
  targetNamespace: coredns
  chart:
    spec:
      chart: coredns
      version: '1.45.0'
      sourceRef:
        kind: HelmRepository
        name: coredns
  values:
    isClusterService: false
    serviceType: LoadBalancer
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.1.11
    env:
    - name: AWS_REGION
      value: us-east-2
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-creds
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-creds
          key: AWS_SECRET_ACCESS_KEY
    prometheus:
      service:
        enabled: true
      monitor:
        enabled: true
        namespace: prometheus
    livenessProbe:
      initialDelaySeconds: 15
    servers:
    - zones:
      - zone: .
        use_tcp: true
      port: 53
      plugins:
      - name: errors
      - name: health
        configBlock: |-
          lameduck 10s
      - name: ready
      - name: route53
        parameters: ${zone}:${hostedZoneId}
        configBlock: |-
          refresh 3m
          fallthrough
      - name: hosts
        configBlock: |-
          192.168.1.12 geo.hivebedrock.network
          192.168.1.12 hivebedrock.network
          192.168.1.12 play.inpvp.net
          192.168.1.12 mco.lbsg.net
          192.168.1.12 play.galaxite.net
          192.168.1.12 play.enchanted.gg
          192.168.1.12 mco.cubecraft.net
          fallthrough
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . 8.8.8.8:53 8.8.4.4:53
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
    