apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: oauth2-proxy
  namespace: flux
spec:
  interval: 10m0s
  url: https://oauth2-proxy.github.io/manifests
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: oauth2-proxy
  targetNamespace: oauth2-proxy
  install:
    createNamespace: true
  chart:
    spec:
      chart: oauth2-proxy
      version: "8.3.3"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
      interval: 5m
  values:
    config:
      configFile: |-
        email_domains = [ "*" ]
        upstreams = [ "file:///dev/null" ]
        github_user = bentastic27
        session_store_type = redis
        redis_connection_url = redis://valkey.oauth2-proxy.svc.cluster.local
