apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: public-gateway
    namespace: istio-system
    sectionName: https
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: internal-gateway
    namespace: istio-system
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: oauth2-proxy
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /oauth2
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  to:
  - group: ""
    kind: Service
    name: oauth2-proxy
