apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: backup-creds
  namespace: wordpress
stringData:
  aws-access-key: ${accessKeyId}
  aws-secret-key: ${secretAccessKey}
  restic-password: ${RESTIC_PASSWORD}
---
apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: backup-test
  namespace: wordpress
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    repoPasswordSecretRef:
      name: backup-creds
      key: restic-password
    s3:
      endpoint: s3.us-east-2.amazonaws.com
      bucket: bentastic27-homelab-buckets
      accessKeyIDSecretRef:
        name: backup-creds
        key: aws-access-key
      secretAccessKeySecretRef:
        name: backup-creds
        key: aws-secret-key
