apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blog-base
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: blog-base
  targetNamespace: blog
  install:
    createNamespace: false
  chartRef:
    kind: HelmChart
    name: base-components
  values:
    hostname: blog.beansnet.net
    clusterIssuer: letsencrypt-dns-cluster-issuer
    targetService:
      name: wordpress
      port: 80
    authPolicy:
      allowAll: false
  dependsOn:
  - name: ingress-gateway
