apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blog-mariadb
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: mariadb
  targetNamespace: blog
  chart:
    spec:
      chart: mariadb
      version: '20.2.2'
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 30m
  values:
    global:
      defaultStorageClass: openebs-hostpath
    auth:
      existingSecret: mariadb
    primary:
      resources:
        limits:
          memory: 512Mi
  dependsOn:
  - name: istiod
