apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux
spec:
  interval: 10m0s
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: metallb
  targetNamespace: metallb
  install:
    createNamespace: true
  chart:
    spec:
      chart: metallb
      version: '0.14.9'
      sourceRef:
        kind: HelmRepository
        name: metallb
