apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-manifests
  namespace: flux
spec:
  interval: 10m0s
  path: "./flux/metallb/manifests"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
