apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wp
  namespace: flux
spec:
  interval: 10m0s
  path: "./flux/wp"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: common-configs
