apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
 name: allow
 namespace: wordpress
spec:
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/istio-system/sa/ingressgateway-service-account
    - source:
        namespaces:
        - wordpress
