apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
 name: deny-ap-admin
 namespace: wordpress
spec:
  action: DENY
  selector:
    matchLabels:
      app: wordpress
  rules:
  - from:
    - source:
        notRemoteIpBlocks:
        - "50.4.72.65"
    to:
    - operation:
        paths:
        - "/wp-admin*"
        ports:
        - "80"
