apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
 name: deny-wp-admin
 namespace: wordpress
spec:
  action: DENY
  selector:
    matchLabels:
      app: wordpress
  rules:
  - from:
    - source:
        notRemoteIpBlocks:
        - "${publicIp:=0.0.0.0/0}"
    to:
    - operation:
        paths:
        - "/wp-admin*"
        ports:
        - "80"
        - "8080"
