apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
 name: restrict-wp-admin
 namespace: wordpress
spec:
  action: ALLOW
  targetRefs:
  - kind: Service
    group: ""
    name: wordpress
  rules:
  - from:
    - source:
        notRemoteIpBlocks:
        - "${publicIp:=0.0.0.0/0}"
    to:
    - operation:
        paths:
        - "/wp-admin*"
  - to:
    - operation:
        notPaths:
        - "/wp-admin*"
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-same-ns-services
  namespace: wordpress
spec:
  action: ALLOW
  targetRefs:
  - kind: Service
    group: ""
    name: wordpress
  - kind: Service
    group: ""
    name: mariadb
  - kind: Service
    group: ""
    name: mariadb-headless
  - kind: Service
    group: ""
    name: memcached
  rules:
  - from:
    - source:
        namespaces:
        - wordpress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-inbound-http
  namespace: wordpress
spec:
  podSelector:
    matchLabels:
      app: wordpress
  ingress:
  - ports:
    - port: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-hbone
  namespace: wordpress
spec:
  podSelector: {}
  ingress:
  - ports:
    - port: 15008
      protocol: TCP
  egress:
  - ports:
    - port: 15008
      protocol: TCP