apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wp-mariadb
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: mariadb
  targetNamespace: wordpress
  chart:
    spec:
      chart: mariadb
      version: '20.2.2'
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 5m
  values:
    auth:
      database: wordpress
    global:
      defaultStorageClass: openebs-hostpath
    primary:
      resources:
        limits:
          memory: 512Mi
    networkPolicy:
      enabled: false
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: mariadb
  namespace: wordpress
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: mariadb
  mtls:
    mode: STRICT
  portLevelMtls:
    3306:
      mode: DISABLE