apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wp-mariadb
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: mariadb
  targetNamespace: wordpress
  chart:
    spec:
      chart: mariadb
      version: '20.2.2'
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 5m
  values:
    auth:
      database: wordpress
    global:
      defaultStorageClass: openebs-hostpath
    primary:
      resources:
        limits:
          memory: 512Mi
    networkPolicy:
      enabled: false
  # postRenderers:
  # - kustomize:
  #     patches:
  #     - target:
  #         version: v1
  #         kind: Service
  #         name: mariadb
  #       patch: |
  #         - op: add
  #           path: /metadata/labels/istio.io~1ingress-use-waypoint
  #           value: "true"
  #     - target:
  #         version: v1
  #         kind: Service
  #         name: mariadb-headless
  #       patch: |
  #         - op: add
  #           path: /metadata/labels/istio.io~1ingress-use-waypoint
  #           value: "true"