apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wp-mariadb
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: mariadb
  targetNamespace: wordpress
  chart:
    spec:
      chart: mariadb
      version: '20.2.2'
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 5m
  values:
    auth:
      database: wordpress
    global:
      defaultStorageClass: openebs-hostpath
    # commonLabels:
    #   istio.io/dataplane-mode: none
    primary:
      resources:
        limits:
          memory: 512Mi
  dependsOn:
  - name: istiod
