apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wp-memcached
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: memcached
  targetNamespace: wordpress
  chart:
    spec:
      chart: memcached
      version: '7.6.1'
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 5m
  values:
    networkPolicy:
      enabled: false
