apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
  namespace: wordpress
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      # annotations:
      #   traffic.sidecar.istio.io/excludeOutboundPorts: "3306"
      labels:
        app: wordpress
        mariadb-client: "true"
        memcached-client: "true"
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.7.2-php8.1-apache
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb.wordpress.svc.cluster.local
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: mariadb-root-password
        volumeMounts:
        - mountPath: /var/www/html
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: wordpress
