apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
  namespace: wordpress
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
        mariadb-client: "true"
        memcached-client: "true"
    spec:
      containers:
      - name: wordpress
        image: bitnami/wordpress:6.8.1
        ports:
        - containerPort: 8080
        env:
        - name: MARIADB_HOST
          value: mariadb.wordpress.svc.cluster.local
        - name: PORT
          value: "3306"
        - name: WORDPRESS_DATABASE_USER
          value: root
        - name: WORDPRESS_DATABASE_NAME
          value: wordpress
        - name: WORDPRESS_EXTRA_WP_CONFIG_CONTENT
          value: "define('WP_CACHE', true);"
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: mariadb-root-password
        volumeMounts:
        - mountPath: /bitnami/wordpress
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: wordpress
