apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: keycloak-operator
  namespace: keycloak
spec:
  action: ALLOW
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak-operator
  rules:
  - []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: keycloak-operator
  namespace: keycloak
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: keycloak-operator
  egress:
  - ports:
    - port: 443
      protocol: TCP
  ingress:
  - ports:
    - port: 80
      protocol: TCP