apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: otterwiki
  namespace: flux
spec:
  interval: 10m0s
  path: "./flux/otterwiki/yaml"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
  dependsOn:
  - name: istio
  - name: oauth2-proxy
  postBuild:
    substituteFrom:
    - kind: Secret
      name: route53-credentials-secret
    - kind: Secret
      name: restic-password
