apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: backup-creds
  namespace: otterwiki
stringData:
  aws-access-key: ${accessKeyId}
  aws-secret-key: ${secretAccessKey}
  restic-password: ${RESTIC_PASSWORD}
---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: backup
  namespace: otterwiki
spec:
  backup:
    schedule: '00 01 * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
  backend:
    repoPasswordSecretRef:
      name: backup-creds
      key: restic-password
    s3:
      endpoint: s3.us-east-2.amazonaws.com
      bucket: bentastic27-homelab-backups/otterwiki
      accessKeyIDSecretRef:
        name: backup-creds
        key: aws-access-key
      secretAccessKeySecretRef:
        name: backup-creds
        key: aws-secret-key
  check:
    schedule: '0 2 * * *'
  prune:
    schedule: '0 3 * * *'
    retention:
      keepLast: 5
