apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otterwiki-base
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: otterwiki-base
  targetNamespace: otterwiki
  install:
    createNamespace: false
  chartRef:
    kind: HelmChart
    name: base-components
  values:
    hostnames:
    - otterwiki.beansnet.net
    - ow.beansnet.net
    targetService:
      name: otterwiki
      port: 80
  dependsOn:
  - name: cert-manager
