apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: bentastic27@gmail.com
    privateKeySecretRef:
      name: letsencrypt-dns-cluster-issuer
    solvers:
    - dns01:
        route53:
          region: us-east-2
          hostedZoneID: Z0466241UWHPLQN701UT
          accessKeyIDSecretRef:
            name: route53-credentials-secret
            key: access-key-id
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: secret-access-key