apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux
spec:
  interval: 10m
  timeout: 5m
  releaseName: cert-manager
  targetNamespace: cert-manager
  install:
    createNamespace: true
  values:
    crds:
      enabled: true
  chart:
    spec:
      chart: cert-manager
      version: 'v1.16.3'
      sourceRef:
        kind: HelmRepository
        name: cert-manager
