apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-manifests
  namespace: flux
spec:
  interval: 10m0s
  path: "./flux/cert-manager/manifests"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
  dependsOn:
  - name: cert-manager